---
title: "Anomaly detection in water-quality variables utilising information from the nearby sensors"
subtitle: "Abstract"
author: "Puwasala Gamakumara"
date: "13/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Low-cost in-situ sensors are used to monitor and manage the quality of water by taking measurements from different water-quality variables in high frequency. The data generated by these sensors are prone to errors due to mis-calibration, bio-fouling, weakening battery
charge or any other technical failures. We propose a novel statistical method based on Generalised Additive Models (GAM), to detect anomalies in these water-quality variables. Proposed method involve building a GAM to the water-quality variable measured in downstream, using related lagged predictors from the upstream sensor. The lag time is estimated using cross-correlation methods. Residuals from the proposed model are then used to detect anomalies following Peak Over Threshold method based on Extreme Value Theory. We also show that utilising the information from the upstream sensor minimises the false negative rate than just using predictors from the same sensor location. 



